name: crop_yield_prediction
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - decorator=4.3.0
  - entrypoints=0.3
  - expat=2.2.6
  - intel-openmp=2019.1
  - ipykernel=5.1.0
  - ipython=7.2.0
  - ipython_genutils=0.2.0
  - jedi=0.13.2
  - jinja2=2.10
  - jsonschema=2.6.0
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - libgfortran=3.0.1
  - libsodium=1.0.16
  - markupsafe=1.1.0
  - mistune=0.8.4
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - notebook=5.7.4
  - numpy=1.15.4
  - numpy-base=1.15.4
  - pandas=0.23.4
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.1
  - pcre=8.42
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - prometheus_client=0.5.0
  - prompt_toolkit=2.0.7
  - ptyprocess=0.6.0
  - pygments=2.3.1
  - python-dateutil=2.7.5
  - pytz=2018.9
  - pyzmq=17.1.2
  - scipy=1.2.0
  - send2trash=1.5.0
  - terminado=0.8.1
  - testpath=0.4.2
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - zeromq=4.2.5
  - affine=2.2.2
  - asn1crypto=0.24.0
  - attrs=18.2.0
  - boost-cpp=1.68.0
  - boto3=1.9.86
  - botocore=1.12.86
  - bzip2=1.0.6
  - ca-certificates=2018.11.29
  - cachetools=2.1.0
  - cairo=1.16.0
  - certifi=2018.11.29
  - cffi=1.11.5
  - click=7.0
  - click-plugins=1.0.4
  - cligj=0.5.0
  - cryptography=2.5
  - curl=7.63.0
  - cycler=0.10.0
  - docutils=0.14
  - earthengine-api=0.1.164
  - fire=0.1.3
  - fontconfig=2.13.1
  - freetype=2.9.1
  - freexl=1.0.5
  - gdal=2.4.0
  - geos=3.7.1
  - geotiff=1.4.3
  - gettext=0.19.8.1
  - giflib=5.1.4
  - glib=2.58.2
  - google-api-python-client=1.7.7
  - google-auth=1.6.2
  - google-auth-httplib2=0.0.3
  - hdf4=4.2.13
  - hdf5=1.10.4
  - httplib2=0.12.0
  - icu=58.2
  - idna=2.8
  - jmespath=0.9.3
  - jpeg=9c
  - json-c=0.13.1
  - kealib=1.4.10
  - kiwisolver=1.0.1
  - krb5=1.16.3
  - libcurl=7.63.0
  - libcxx=7.0.0
  - libdap4=3.19.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgdal=2.4.0
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.6.2
  - libpng=1.6.36
  - libpq=10.6
  - libspatialite=4.3.0a
  - libssh2=1.8.0
  - libtiff=4.0.10
  - libxml2=2.9.8
  - llvm-meta=7.0.0
  - matplotlib=3.0.2
  - matplotlib-base=3.0.2
  - ncurses=6.1
  - oauth2client=4.1.2
  - openjpeg=2.3.0
  - openssl=1.0.2p
  - pip=18.1
  - pixman=0.34.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=10.6
  - proj4=5.2.0
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.3
  - pycparser=2.19
  - pyopenssl=18.0.0
  - pyparsing=2.3.1
  - pysocks=1.6.8
  - python=3.7.1
  - rasterio=1.0.15
  - readline=7.0
  - rsa=3.4.2
  - s3transfer=0.1.13
  - setuptools=40.6.3
  - simplejson=3.16.0
  - six=1.12.0
  - snuggs=1.4.1
  - sqlite=3.26.0
  - tk=8.6.9
  - tornado=5.1.1
  - tqdm=4.30.0
  - tzcode=2018g
  - uritemplate=3.0.0
  - urllib3=1.24.1
  - wheel=0.32.3
  - xerces-c=3.2.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.3
  - ninja=1.8.2
  - pytorch=1.0.0
  - pip:
    - torch==1.0.0
